import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import SocketInitializer from "@/components/component/socket-initializer";

const fontHeading = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-heading",
});

const fontBody = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-body",
});

export const metadata: Metadata = {
	title: "Triviafy",
	description: "Generated by Andrew McMillan",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn("antialiased", fontHeading.variable, fontBody.variable)}
			>
				{/* <SocketInitializer /> */}
				<main className="flex min-h-screen flex-col items-center justify-start w-full">
					{children}
				</main>
			</body>
		</html>
	);
}
